.TH CLIENT 1 "September 2025" "libmyutils" "User Commands"
.SH NAME
client \- run the myutils client program
.SH SYNOPSIS
.B client
.SH DESCRIPTION
Runs the myutils client program, which demonstrates the use of custom string
and file utility functions implemented in libmyutils.
.SH AUTHOR
Written by Fahad Rahman
